CREATE DATABASE GRUPO_6_DB;
USE GRUPO_6_DB;
CREATE TABLE AVION
(
	ID INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(30) NOT NULL,
	CAPACIDAD INT NOT NULL
);
CREATE TABLE CLIENTE
(
	ID INT NOT NULL PRIMARY KEY,
	DIRECCION VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	TELEFONO VARCHAR(30) NOT NULL,
	DNI VARCHAR(8) NOT NULL,
	NOMBRE VARCHAR(40) NOT NULL,
	APELLIDO VARCHAR(40) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL
	
);
CREATE TABLE VUELO
(
	ID INT NOT NULL PRIMARY KEY,
	ID_AVION INT NULL REFERENCES AVION(ID),
	DESDE VARCHAR(30) NOT NULL,
	HACIA VARCHAR(30) NOT NULL,
	HORARIO_PARTIDA DATE,
	HORARIO_LLEGADA DATE
);
CREATE TABLE PAQUETE
(
	ID INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(100),
	PRECIO NUMERIC(8,2) NOT NULL,
	CANT_PERSONAS INT NOT NULL,
	ID_VUELO INT NOT NULL REFERENCES VUELO(ID)
);
CREATE TABLE RESERVA
(
	ID INT NOT NULL PRIMARY KEY,
	ID_PAQUETE INT NOT NULL REFERENCES PAQUETE(ID)
);
CREATE TABLE RESERVA_CLIENTE
(
	ID_CLIENTE INT NOT NULL REFERENCES CLIENTE(ID),
	ID_RESERVA INT NOT NULL REFERENCES RESERVA(ID),
	PRIMARY KEY(ID_CLIENTE,ID_RESERVA)
);


INSERT INTO AVION VALUES(1,'TANGO01',50);
INSERT INTO AVION VALUES(2,'TANGO02',50);
INSERT INTO AVION VALUES(3,'TANGO03',50);

INSERT INTO CLIENTE (`ID`, `DIRECCION`, `EMAIL`, `TELEFONO`, `DNI`, `NOMBRE`, `APELLIDO`, `FECHA_NACIMIENTO`) VALUES (1, 'Calle falsa 123', 'admin@admin.com.ar', '11111111111', '11111111', 'Guillermo', 'Telijo', '1994-04-11');
INSERT INTO CLIENTE (`ID`, `DIRECCION`, `EMAIL`, `TELEFONO`, `DNI`, `NOMBRE`, `APELLIDO`, `FECHA_NACIMIENTO`)VALUES (2, 'Av Siempre Viva', 'root@admin.com.ar', '2222222222', '22222222', 'Esteban', 'Quito', '1994-10-18');

SELECT COUNT(RESERVA_CLIENTE.ID)

